sudo: required
services:
  - docker
before_install:
  - docker build -t yakushou730/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run yakushou730/react-test npm test -- --coverage
after_success:
  - docker build -t yakushou730/multi-client ./client
  - docker build -t yakushou730/multi-nginx ./nginx
  - docker build -t yakushou730/multi-server ./server
  - docker build -t yakushou730/multi-worker ./worker
  # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yakushou730/multi-client
  - docker push yakushou730/multi-nginx
  - docker push yakushou730/multi-server
  - docker push yakushou730/multi-worker